### PR TITLE
Pipe example

### PR DESCRIPTION
**Pull request by MatthewVita**
@robertdown we are using your tool for QA'ing the OpenEMR Cloud Express. This is what I am doing... what are your thoughts?

### CODE REVIEW

**Comment by MatthewVita** [comment]
Also, if I'm reading the source code right, there is a way to specific a `count`... maybe that's the better approach? :)

**Comment by robertdown** [comment]
You should be able to specify number of records in the script.

Use `demodata patients --count=1000 > file.sql`

**Comment by bradymiller** [comment]
Wasn't there a bug where this crapped out if went higher than 500 patients or so?

**Comment by MatthewVita** [comment]
@bradymiller you missed the opportunity to use the 💩 emoji in place of the word "crap"!

**Comment by robertdown** [comment]
Yep, no idea why

**Pull request closed without merging**
